name: Tag & release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
  # push:
  #   branches:
  #     - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.com/
      - name: Install dependencies and build 🔧
        run: yarn install --immutable && yarn build
      # - name: Extract version
      #   id: extract_version
      #   uses: Saionaro/extract-package-version@v1.0.6
      # - name: Print version
      #   run: echo ${{ steps.extract_version.outputs.version }}
      - name: Tag & release 🚀
        uses: avakar/tag-and-release@v1
        with:
          # tag_name: ${{ format('v{0}', steps.extract_version.outputs.version) }}
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ format('Release {0}', github.event.inputs.version) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
